const interestsData = [
    { id: 1, name: 'Soccer' },
    { id: 2, name: 'Music' },
    { id: 3, name: 'Cooking' },
    { id: 4, name: 'Travel' },
    { id: 5, name: 'Hiking' },
    { id: 6, name: 'Reading' },
    { id: 7, name: 'Gaming' },
    { id: 8, name: 'Photography' },
    { id: 9, name: 'Art' },
    { id: 10, name: 'Dancing' },
    { id: 11, name: 'Swimming' },
    { id: 12, name: 'Movies' },
    { id: 13, name: 'Coding' },
    { id: 14, name: 'Fashion' },
    { id: 15, name: 'Yoga' },
    { id: 16, name: 'Basketball' },
    { id: 17, name: 'Gardening' },
    { id: 18, name: 'Meditation' },
    { id: 19, name: 'Foodie' },
    { id: 20, name: 'Cycling' },
    { id: 21, name: 'Tech' },
    { id: 22, name: 'Crafts' },
    { id: 23, name: 'Singing' },
    { id: 24, name: 'Animals' },
    { id: 25, name: 'Science' },
    { id: 26, name: 'Politics' },
    { id: 27, name: 'History' },
    { id: 28, name: 'Volunteering' },
    { id: 29, name: 'Fitness' },
    { id: 30, name: 'DIY' },
    { id: 31, name: 'Pets' },
    { id: 32, name: 'Surfing' },
    { id: 33, name: 'Skiing' },
    { id: 34, name: 'Writing' },
    { id: 35, name: 'Coffee' },
    { id: 36, name: 'Wine' },
    { id: 37, name: 'Shopping' },
    { id: 38, name: 'Motorcycles' },
    { id: 39, name: 'Travelling' },
    { id: 40, name: 'Nature' },
    { id: 41, name: 'Languages' },
    { id: 42, name: 'Books' },
    { id: 43, name: 'Cars' },
    { id: 44, name: 'Astronomy' },
    { id: 45, name: 'Cookbooks' },
    { id: 46, name: 'Mountaineering' },
    { id: 47, name: 'Fitness Training' },
    { id: 48, name: 'Collecting' },
    { id: 49, name: 'Horse Riding' },
    { id: 50, name: 'Bird Watching' },
  ];
  
  export default interestsData;
  